"""Backend-neutral contracts for the AIC signal harness."""

from aic_signal_harness.backfill import (
    LegacyRunBackfill,
    backfill_legacy_replay_policy_eval,
)
from aic_signal_harness.artifacts import (
    HarnessIOError,
    read_json,
    sha256_file,
    write_json,
)
from aic_signal_harness.hdf5_dataset import (
    Hdf5DatasetReport,
    Hdf5DatasetStats,
    Hdf5DatasetThresholds,
    PER_STEP_HDF5_DATASET_KEYS,
    REQUIRED_HDF5_DATASET_KEYS,
)
from aic_signal_harness.ledger import (
    LedgerDatasetSummary,
    LedgerEntry,
    LedgerMetric,
    LedgerMetricGoal,
    append_ledger_entry,
    read_ledger_entries,
)
from aic_signal_harness.mcap_eval import (
    McapEvalBundleReport,
    McapEvalFirstContact,
    McapEvalTaskHints,
    McapEvalTrialReport,
)
from aic_signal_harness.manifest import RunManifest, RunStatus
from aic_signal_harness.next_experiment import (
    NextExperimentAction,
    NextExperimentCandidate,
    NextExperimentCandidateKind,
    NextExperimentDecision,
    NextExperimentPriority,
    NextExperimentReport,
)
from aic_signal_harness.promotion import (
    PromotionDecision,
    PromotionDecisionKind,
    PromotionGoal,
    PromotionMetric,
    read_promotion_decision,
    write_baseline_decision,
    write_promotion_decision,
)
from aic_signal_harness.failure import (
    FailureKind,
    FailureLabel,
    FailureReport,
    FailureSeverity,
)
from aic_signal_harness.reducers import (
    Hdf5DatasetReduction,
    McapEvalReduction,
    RewardFailureReduction,
    ScoringYamlReduction,
    analyze_mcap_eval_bundle,
    attach_scoring_yaml_reduction,
    build_ledger_entry,
    derive_next_experiment_report,
    derive_reward_failure_reports,
    promote_ledger_entry,
    reduce_mcap_eval_bundle,
    reduce_hdf5_dataset,
    reduce_scoring_yaml,
    validate_hdf5_dataset,
)
from aic_signal_harness.reward import RewardReport, RewardSignalKind, RewardTerm
from aic_signal_harness.schemas import (
    ArtifactRef,
    BackendKind,
    ExperimentSpec,
    LeakageClass,
    PolicyBackendSpec,
    RuntimeBoundaryProof,
    RuntimeRole,
    SchemaValidationError,
    SimulatorKind,
    TrainingSourceKind,
    experiment_spec_from_json,
    experiment_spec_to_json,
    utc_now_iso,
)
from aic_signal_harness.scoring import ScoreReport, TrialScore, parse_scoring_yaml

__all__ = [
    "ArtifactRef",
    "BackendKind",
    "ExperimentSpec",
    "FailureKind",
    "FailureLabel",
    "FailureReport",
    "FailureSeverity",
    "Hdf5DatasetReduction",
    "Hdf5DatasetReport",
    "Hdf5DatasetStats",
    "Hdf5DatasetThresholds",
    "HarnessIOError",
    "LeakageClass",
    "LedgerDatasetSummary",
    "LedgerEntry",
    "LedgerMetric",
    "LedgerMetricGoal",
    "McapEvalBundleReport",
    "McapEvalFirstContact",
    "McapEvalReduction",
    "McapEvalTaskHints",
    "McapEvalTrialReport",
    "NextExperimentAction",
    "NextExperimentCandidate",
    "NextExperimentCandidateKind",
    "NextExperimentDecision",
    "NextExperimentPriority",
    "NextExperimentReport",
    "PER_STEP_HDF5_DATASET_KEYS",
    "PolicyBackendSpec",
    "PromotionDecision",
    "PromotionDecisionKind",
    "PromotionGoal",
    "PromotionMetric",
    "REQUIRED_HDF5_DATASET_KEYS",
    "RunManifest",
    "RunStatus",
    "RewardFailureReduction",
    "RewardReport",
    "RewardSignalKind",
    "RewardTerm",
    "ScoringYamlReduction",
    "ScoreReport",
    "RuntimeBoundaryProof",
    "RuntimeRole",
    "SchemaValidationError",
    "SimulatorKind",
    "TrainingSourceKind",
    "TrialScore",
    "analyze_mcap_eval_bundle",
    "append_ledger_entry",
    "attach_scoring_yaml_reduction",
    "backfill_legacy_replay_policy_eval",
    "build_ledger_entry",
    "derive_next_experiment_report",
    "derive_reward_failure_reports",
    "experiment_spec_from_json",
    "experiment_spec_to_json",
    "LegacyRunBackfill",
    "parse_scoring_yaml",
    "promote_ledger_entry",
    "read_ledger_entries",
    "read_json",
    "read_promotion_decision",
    "reduce_mcap_eval_bundle",
    "reduce_hdf5_dataset",
    "reduce_scoring_yaml",
    "sha256_file",
    "utc_now_iso",
    "validate_hdf5_dataset",
    "write_baseline_decision",
    "write_json",
    "write_promotion_decision",
]
